train: /content/drive/MyDrive/dataset/train # train images (relative to 'path') 128 images
val: /content/drive/MyDrive/dataset/val  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
names:
  0: casco
  1: rostro
  2: chaleco


# Download script/URL (optional)
download: https://ultralytics.com/assets/coco128.zip